# Generated by Django 5.2.16 on 2026-07-24 23:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_missing_public_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserPublicProfile = apps.get_model('authentication', 'UserPublicProfile')
    existing_user_ids = UserPublicProfile.objects.values_list('user_id', flat=True)
    UserPublicProfile.objects.bulk_create(
        [
            UserPublicProfile(user_id=user_id)
            for user_id in User.objects.exclude(id__in=existing_user_ids).values_list(
                'id',
                flat=True,
            )
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_user_preferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPublicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=280)),
                ('avatar_url', models.URLField(blank=True, max_length=2048, validators=[django.core.validators.URLValidator(schemes=['https'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_public_profiles',
            },
        ),
        migrations.RunPython(
            create_missing_public_profiles,
            migrations.RunPython.noop,
        ),
    ]
