# Generated by Django 5.2.7 on 2025-10-26 22:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_api",
                    models.CharField(
                        choices=[
                            ("tmdb", "TMDB"),
                            ("igdb", "IGDB"),
                            ("spotify", "Spotify"),
                            ("openlibrary", "OpenLibrary"),
                        ],
                        help_text="External API source",
                        max_length=20,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="Unique ID of the item in the external API",
                        max_length=255,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("MOVIE", "Movie"),
                            ("TV_SHOW", "TV Show"),
                            ("GAME", "Game"),
                            ("ALBUM", "Album"),
                            ("BOOK", "Book"),
                        ],
                        help_text="Content type",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "content_items",
                "indexes": [
                    models.Index(
                        fields=["source_api", "external_id"],
                        name="content_ite_source__798958_idx",
                    ),
                    models.Index(
                        fields=["content_type"], name="content_ite_content_380b34_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_api", "external_id"),
                        name="unique_external_content",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the list", max_length=255),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of the list",
                        null=True,
                    ),
                ),
                (
                    "list_type",
                    models.CharField(
                        choices=[("PERSONAL", "Personal"), ("SHARED", "Shared")],
                        default="PERSONAL",
                        help_text="List type",
                        max_length=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date and time of creation"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Date and time of last update"
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Members of the list (for shared lists)",
                        related_name="member_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Creator and owner of the list",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_lists",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("COMPLETED", "Completed")],
                        default="PENDING",
                        help_text="Status of the item",
                        max_length=10,
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date and time of addition"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="Date and time of completion", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Personal notes about this item",
                        null=True,
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        help_text="User who added this item",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="added_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_item",
                    models.ForeignKey(
                        help_text="Reference to the content",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="list_items",
                        to="content.contentitem",
                    ),
                ),
                (
                    "user_list",
                    models.ForeignKey(
                        help_text="List to which this item belongs",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="content.userlist",
                    ),
                ),
            ],
            options={
                "db_table": "list_items",
                "ordering": ["-added_at"],
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Rating from 0.5 to 10.0 (in increments of 0.5)",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0.5),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, help_text="Optional comment", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date and time of creation"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Date and time of last update"
                    ),
                ),
                (
                    "content_item",
                    models.ForeignKey(
                        help_text="Content being rated",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="content.contentitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who performs the rating",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ratings",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_item", "-created_at"],
                        name="ratings_content_ba94e5_idx",
                    ),
                    models.Index(fields=["user"], name="ratings_user_id_bd9bb9_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "content_item"), name="unique_user_rating"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="userlist",
            index=models.Index(
                fields=["owner", "list_type"], name="user_lists_owner_i_d9e7ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userlist",
            index=models.Index(
                fields=["-created_at"], name="user_lists_created_b06ae3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listitem",
            index=models.Index(
                fields=["user_list", "status"], name="list_items_user_li_6351cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listitem",
            index=models.Index(
                fields=["content_item"], name="list_items_content_db85fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listitem",
            index=models.Index(
                fields=["-added_at"], name="list_items_added_a_6c05e8_idx"
            ),
        ),
    ]
