# Generated by Django 5.2.7 on 2025-10-27 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentitem",
            name="average_rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Average rating score (cached)",
                max_digits=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contentitem",
            name="rating_count",
            field=models.IntegerField(
                default=0, help_text="Total number of ratings (cached)"
            ),
        ),
    ]
