# Generated by Django 5.2.7 on 2025-10-27 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_list_invitation"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="listinvitation",
            new_name="list_invita_invitee_dd3d27_idx",
            old_name="list_invita_invitee_idx",
        ),
        migrations.RenameIndex(
            model_name="listinvitation",
            new_name="list_invita_user_li_b31fd1_idx",
            old_name="list_invita_userlist_idx",
        ),
        migrations.RenameIndex(
            model_name="listinvitation",
            new_name="list_invita_created_c10b06_idx",
            old_name="list_invita_created_idx",
        ),
    ]
