# Generated by Django 5.2.7 on 2025-10-30 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_list_item_order"),
        ("content", "0005_alter_average_rating_max_digits"),
    ]

    operations = []
