# Generated by Django 5.2.7 on 2025-11-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_merge_20251030_0155"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listitem",
            options={"ordering": ["list_order", "-added_at"]},
        ),
        migrations.RemoveConstraint(
            model_name="contentitem",
            name="unique_external_content",
        ),
        migrations.RenameIndex(
            model_name="listitem",
            new_name="list_items_user_li_4b8b88_idx",
            old_name="content_lis_user_li_orde_idx",
        ),
        migrations.AddConstraint(
            model_name="contentitem",
            constraint=models.UniqueConstraint(
                fields=("source_api", "external_id", "content_type"),
                name="unique_external_content",
            ),
        ),
    ]
