# Generated by Django 5.2.7 on 2025-11-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_alter_listitem_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentitem",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("MOVIE", "Movie"),
                    ("TV_SHOW", "TV Show"),
                    ("SEASON", "Season"),
                    ("GAME", "Game"),
                    ("ALBUM", "Album"),
                    ("BOOK", "Book"),
                ],
                help_text="Content type",
                max_length=20,
            ),
        ),
    ]
