# Generated by Django 5.2.7 on 2025-11-24 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_alter_contentitem_content_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listitem",
            name="notes",
        ),
    ]
