# Generated by Django 5.2.13 on 2026-04-11 23:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_remove_notes_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="listitem",
            constraint=models.UniqueConstraint(
                fields=("user_list", "content_item"), name="unique_item_per_list"
            ),
        ),
    ]
