# Generated by Django 5.2.13 on 2026-04-18 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0010_add_unique_item_per_list"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentItemBrowseMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_title",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Primary title used for display and sorting",
                        max_length=500,
                    ),
                ),
                (
                    "artist",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Primary artist name (ALBUM)",
                        max_length=500,
                    ),
                ),
                (
                    "album_title",
                    models.CharField(
                        blank=True, help_text="Album title (ALBUM)", max_length=500
                    ),
                ),
                (
                    "release_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Primary release/publish date in canonical form",
                        null=True,
                    ),
                ),
                (
                    "last_refreshed_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="When this metadata was last refreshed from the upstream API",
                    ),
                ),
                (
                    "source_payload_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash of the upstream payload used to detect changes during rehydration",
                        max_length=64,
                    ),
                ),
                (
                    "content_item",
                    models.OneToOneField(
                        help_text="Content item this browse metadata belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="browse_meta",
                        to="content.contentitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content item browse metadata",
                "verbose_name_plural": "Content item browse metadata",
                "db_table": "content_item_browse_metadata",
            },
        ),
    ]
