# Generated by Django 5.2.16 on 2026-07-24 23:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_per_type_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('on_hold', 'On hold'), ('dropped', 'Dropped')], default='backlog', max_length=20)),
                ('last_completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('favorited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_content_tracking',
            },
        ),
        migrations.AddField(
            model_name='rating',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether the rating currently contributes to public aggregates'),
        ),
        migrations.AddField(
            model_name='rating',
            name='spoiler',
            field=models.BooleanField(default=False, help_text='Whether the review text contains spoilers'),
        ),
        migrations.AddField(
            model_name='seasondetail',
            name='tv_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season_children', to='content.contentitem'),
        ),
        migrations.AddField(
            model_name='userlist',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], db_index=True, default='PRIVATE', help_text='Whether the list is publicly readable', max_length=10),
        ),
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.TextField(blank=True, help_text='Optional comment', null=True, validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['content_item', 'is_active'], name='ratings_content_d26ca3_idx'),
        ),
        migrations.AddIndex(
            model_name='userlist',
            index=models.Index(fields=['owner', 'visibility'], name='user_lists_owner_i_c2d547_idx'),
        ),
        migrations.AddField(
            model_name='usercontenttracking',
            name='content_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tracking', to='content.contentitem'),
        ),
        migrations.AddField(
            model_name='usercontenttracking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_tracking', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='usercontenttracking',
            index=models.Index(fields=['user', 'status', '-last_completed_at'], name='tracking_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='usercontenttracking',
            index=models.Index(fields=['user', 'is_favorite'], name='tracking_user_favorite_idx'),
        ),
        migrations.AddConstraint(
            model_name='usercontenttracking',
            constraint=models.UniqueConstraint(fields=('user', 'content_item'), name='unique_user_content_tracking'),
        ),
        migrations.AddConstraint(
            model_name='usercontenttracking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('favorited_at__isnull', False), ('is_favorite', True)), models.Q(('favorited_at__isnull', True), ('is_favorite', False)), _connector='OR'), name='tracking_favorite_date_consistent'),
        ),
    ]
