# Generated by Django 5.2.16 on 2026-09-21 17:19

import content.settings_defaults
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_list_invitation_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentModerationJudgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_data_hash', models.CharField(help_text='Hash of the normalized text inputs used for this judgment', max_length=64)),
                ('model_name', models.CharField(help_text='Exact resolved model version that produced this judgment (e.g. jev-1.13.0)', max_length=64)),
                ('question_revision', models.CharField(help_text='Semantic revision of the Jev questions and criteria', max_length=32)),
                ('policy_revision', models.CharField(default=content.settings_defaults.current_policy_revision, help_text='Semantic revision of the code-owned mapping applied to the raw answers', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('error', 'Error'), ('stale', 'Stale')], default='pending', max_length=16)),
                ('classification', models.CharField(choices=[('safe_for_automatic_discovery', 'Safe for automatic discovery'), ('explicit_or_sensitive', 'Explicit or sensitive'), ('needs_review', 'Needs review'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Raw typed response data (nouls, probabilities, usage); no provider payloads')),
                ('error_code', models.CharField(blank=True, help_text='Machine-readable failure code, e.g. typesafe_timeout', max_length=64)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_judgments', to='content.contentitem')),
            ],
            options={
                'verbose_name': 'content moderation judgment',
                'verbose_name_plural': 'content moderation judgments',
                'db_table': 'content_moderation_judgment',
                'indexes': [models.Index(fields=['content_item', 'status'], name='moderation_item_status_idx'), models.Index(fields=['status', 'classification'], name='moderation_status_class_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_item', 'source_data_hash', 'model_name', 'question_revision'), name='unique_moderation_judgment_identity')],
            },
        ),
    ]
