# Generated by Django 5.2.16 on 2026-09-23 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_contentitem_current_moderation_source_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentModerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_data_hash', models.CharField(max_length=64)),
                ('requested_model', models.CharField(max_length=64)),
                ('question_revision', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('leased', 'Leased'), ('retry', 'Retry'), ('done', 'Done'), ('superseded', 'Superseded'), ('failed', 'Failed'), ('outcome_unknown', 'Outcome unknown')], default='queued', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField()),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_jobs', to='content.contentitem')),
            ],
            options={
                'db_table': 'content_moderation_job',
                'indexes': [models.Index(fields=['status', 'available_at', 'id'], name='moderation_job_ready_idx'), models.Index(fields=['content_item', 'status'], name='moderation_job_item_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_item', 'source_data_hash', 'requested_model', 'question_revision'), name='unique_moderation_job_identity')],
            },
        ),
    ]
