# Generated by Django 5.2.16 on 2026-09-23 15:47

import django.db.models.deletion
from django.db import migrations, models


def create_admission_cursor(apps, schema_editor):
    apps.get_model('content', 'ContentMetadataPreparationCursor').objects.get_or_create(pk=1)


def remove_admission_cursor(apps, schema_editor):
    apps.get_model('content', 'ContentMetadataPreparationCursor').objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_contentmoderationjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentMetadataPreparationCursor',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('last_admitted_content_item_id', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'content_metadata_preparation_cursor',
            },
        ),
        migrations.CreateModel(
            name='ContentMetadataPreparationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('leased', 'Leased'), ('retry', 'Retry'), ('done', 'Done'), ('superseded', 'Superseded'), ('failed', 'Failed'), ('outcome_unknown', 'Outcome unknown')], default='queued', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField()),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('content_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_preparation_job', to='content.contentitem')),
            ],
            options={
                'db_table': 'content_metadata_preparation_job',
                'indexes': [models.Index(fields=['status', 'available_at', 'id'], name='metadata_prep_ready_idx')],
            },
        ),
        migrations.RunPython(create_admission_cursor, reverse_code=remove_admission_cursor),
    ]
