# Generated by Django 5.2.16 on 2026-09-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_contentmetadatapreparationcursor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetail',
            name='subjects',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='gamedetail',
            name='age_ratings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='gamedetail',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='moviedetail',
            name='adult',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moviedetail',
            name='certifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='moviedetail',
            name='genres',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='moviedetail',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='track',
            name='explicit',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tvshowdetail',
            name='adult',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tvshowdetail',
            name='certifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tvshowdetail',
            name='genres',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tvshowdetail',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
