export const ADJECTIVES = [
    "Epic",
    "Cosmic",
    "Chill",
    "Midnight",
    "Neon",
    "Retro",
    "Secret",
    "Golden",
    "Hidden",
    "Lost",
    "Future",
    "Daily",
    "Weekly",
    "Monthly",
    "Ultimate",
    "Essential",
    "Curated",
    "Favorite",
    "Top",
    "Best",
    "Dreamy",
    "Electric",
    "Sonic",
    "Visual",
    "Cinematic",
    "Literary",
    "Gaming",
    "Binge-worthy",
    "Must-see",
    "Classic",
];

export const NOUNS = [
    "Collection",
    "Selection",
    "Mix",
    "Stash",
    "Vault",
    "Library",
    "Queue",
    "Playlist",
    "Anthology",
    "Chronicles",
    "Vibes",
    "Journey",
    "Quest",
    "Adventure",
    "Saga",
    "Universe",
    "Dimension",
    "Zone",
    "Corner",
    "Spot",
    "Haven",
    "Retreat",
    "Lounge",
    "Club",
    "Society",
    "Archive",
    "Treasury",
    "Catalog",
    "Index",
    "Digest",
];

export function generateRandomListName(): string {
    const adjective = ADJECTIVES[Math.floor(Math.random() * ADJECTIVES.length)];
    const noun = NOUNS[Math.floor(Math.random() * NOUNS.length)];
    return `${adjective} ${noun}`;
}
