# Generated by Django 5.2.7 on 2025-10-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "content",
            "0004_rename_list_invita_invitee_idx_list_invita_invitee_dd3d27_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentitem",
            name="average_rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Average rating score (cached)",
                max_digits=4,
                null=True,
            ),
        ),
    ]
