# Generated by Django 5.2.11 on 2026-04-19 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0011_contentitembrowsemetadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "content_game_mode",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "content_genre",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "content_theme",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AlbumDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=500)),
                ("album_type", models.CharField(blank=True, max_length=64)),
                ("total_tracks", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("image_url", models.URLField(blank=True, max_length=500)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("external_url", models.URLField(blank=True, max_length=500)),
                (
                    "last_refreshed_at",
                    models.DateTimeField(auto_now=True, db_index=True),
                ),
                ("source_payload_hash", models.CharField(blank=True, max_length=64)),
                (
                    "content_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="album_detail",
                        to="content.contentitem",
                    ),
                ),
            ],
            options={
                "db_table": "content_album_detail",
            },
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("slug", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "content_author",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="content_aut_name_b63d73_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="BookDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                ("pages", models.PositiveIntegerField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, max_length=500)),
                ("release_date", models.DateField(blank=True, null=True)),
                (
                    "last_refreshed_at",
                    models.DateTimeField(auto_now=True, db_index=True),
                ),
                ("source_payload_hash", models.CharField(blank=True, max_length=64)),
                (
                    "content_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_detail",
                        to="content.contentitem",
                    ),
                ),
            ],
            options={
                "db_table": "content_book_detail",
            },
        ),
        migrations.CreateModel(
            name="GameDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=500)),
                ("game_type", models.CharField(blank=True, max_length=64)),
                ("description", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True, max_length=500)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("series", models.CharField(blank=True, max_length=500)),
                ("play_time_min", models.PositiveIntegerField(blank=True, null=True)),
                ("play_time_max", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "last_refreshed_at",
                    models.DateTimeField(auto_now=True, db_index=True),
                ),
                ("source_payload_hash", models.CharField(blank=True, max_length=64)),
                (
                    "content_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_detail",
                        to="content.contentitem",
                    ),
                ),
                (
                    "game_modes",
                    models.ManyToManyField(
                        blank=True, related_name="games", to="content.gamemode"
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(
                        blank=True, related_name="games", to="content.genre"
                    ),
                ),
                (
                    "themes",
                    models.ManyToManyField(
                        blank=True, related_name="games", to="content.theme"
                    ),
                ),
            ],
            options={
                "db_table": "content_game_detail",
            },
        ),
        migrations.CreateModel(
            name="MovieDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=500)),
                ("original_title", models.CharField(blank=True, max_length=500)),
                ("tagline", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True, max_length=500)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=64)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("imdb_id", models.CharField(blank=True, max_length=64)),
                (
                    "last_refreshed_at",
                    models.DateTimeField(auto_now=True, db_index=True),
                ),
                ("source_payload_hash", models.CharField(blank=True, max_length=64)),
                (
                    "content_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movie_detail",
                        to="content.contentitem",
                    ),
                ),
            ],
            options={
                "db_table": "content_movie_detail",
            },
        ),
        migrations.CreateModel(
            name="SeasonDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season_number", models.IntegerField(default=0)),
                ("tv_show_name", models.CharField(blank=True, max_length=500)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True, max_length=500)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("number_of_episodes", models.PositiveIntegerField(default=0)),
                (
                    "last_refreshed_at",
                    models.DateTimeField(auto_now=True, db_index=True),
                ),
                ("source_payload_hash", models.CharField(blank=True, max_length=64)),
                (
                    "content_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season_detail",
                        to="content.contentitem",
                    ),
                ),
            ],
            options={
                "db_table": "content_season_detail",
            },
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("track_id_external", models.CharField(max_length=128)),
                ("track_number", models.IntegerField()),
                ("title", models.CharField(blank=True, max_length=500)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("external_url", models.URLField(blank=True, max_length=500)),
                (
                    "album_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="content.albumdetail",
                    ),
                ),
            ],
            options={
                "db_table": "content_track",
                "ordering": ["track_number"],
            },
        ),
        migrations.CreateModel(
            name="TrackAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=64)),
                ("position", models.SmallIntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="track_authors",
                        to="content.author",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="track_authors",
                        to="content.track",
                    ),
                ),
            ],
            options={
                "db_table": "content_track_author",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="TvShowDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=500)),
                ("original_title", models.CharField(blank=True, max_length=500)),
                ("tagline", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True, max_length=500)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=64)),
                (
                    "number_of_seasons",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "number_of_episodes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("imdb_id", models.CharField(blank=True, max_length=64)),
                (
                    "last_refreshed_at",
                    models.DateTimeField(auto_now=True, db_index=True),
                ),
                ("source_payload_hash", models.CharField(blank=True, max_length=64)),
                (
                    "content_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tv_show_detail",
                        to="content.contentitem",
                    ),
                ),
            ],
            options={
                "db_table": "content_tv_show_detail",
            },
        ),
        migrations.CreateModel(
            name="ContentItemAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=64)),
                ("position", models.SmallIntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_authors",
                        to="content.author",
                    ),
                ),
                (
                    "content_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_authors",
                        to="content.contentitem",
                    ),
                ),
            ],
            options={
                "db_table": "content_item_author",
                "ordering": ["position", "id"],
                "indexes": [
                    models.Index(
                        fields=["content_item", "role"],
                        name="content_ite_content_ab4556_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content_item", "author", "role"),
                        name="unique_content_item_author_role",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GamePlatform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("image_url", models.URLField(blank=True, max_length=500)),
                (
                    "game_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platforms",
                        to="content.gamedetail",
                    ),
                ),
            ],
            options={
                "db_table": "content_game_platform",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("game_detail", "name"),
                        name="unique_game_platform_per_game",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("poster", "Poster"), ("gallery", "Gallery")],
                        default="poster",
                        max_length=32,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[("standard", "Standard"), ("original", "Original")],
                        default="standard",
                        max_length=32,
                    ),
                ),
                ("image_url", models.URLField(max_length=500)),
                ("position", models.SmallIntegerField(default=0)),
                (
                    "content_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="content.contentitem",
                    ),
                ),
            ],
            options={
                "db_table": "content_image",
                "ordering": ["position", "id"],
                "indexes": [
                    models.Index(
                        fields=["content_item", "type"],
                        name="content_ima_content_160b58_idx",
                    ),
                    models.Index(
                        fields=["content_item", "position"],
                        name="content_ima_content_5481cd_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("episode_id_external", models.CharField(max_length=128)),
                ("episode_number", models.IntegerField()),
                ("season_number", models.IntegerField()),
                ("title", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                ("release_date", models.DateField(blank=True, null=True)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("image_url", models.URLField(blank=True, max_length=500)),
                ("episode_type", models.CharField(blank=True, max_length=64)),
                (
                    "season_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="content.seasondetail",
                    ),
                ),
            ],
            options={
                "db_table": "content_episode",
                "ordering": ["episode_number"],
                "indexes": [
                    models.Index(
                        fields=["season_detail", "episode_number"],
                        name="content_epi_season__cfdffd_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("season_detail", "episode_id_external"),
                        name="unique_episode_per_season",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StreamingPlatform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("stream", "Stream"),
                            ("rent", "Rent"),
                            ("buy", "Buy"),
                        ],
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("image_url", models.URLField(blank=True, max_length=500)),
                ("country_code", models.CharField(blank=True, max_length=8)),
                (
                    "content_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streaming_platforms",
                        to="content.contentitem",
                    ),
                ),
            ],
            options={
                "db_table": "content_streaming_platform",
                "indexes": [
                    models.Index(
                        fields=["content_item", "kind"],
                        name="content_str_content_5cc3f0_idx",
                    ),
                    models.Index(
                        fields=["content_item", "country_code"],
                        name="content_str_content_a7b73b_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content_item", "kind", "name", "country_code"),
                        name="unique_streaming_platform_per_item",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="track",
            index=models.Index(
                fields=["album_detail", "track_number"],
                name="content_tra_album_d_510645_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="track",
            constraint=models.UniqueConstraint(
                fields=("album_detail", "track_id_external"),
                name="unique_track_per_album",
            ),
        ),
        migrations.AddConstraint(
            model_name="trackauthor",
            constraint=models.UniqueConstraint(
                fields=("track", "author", "role"), name="unique_track_author_role"
            ),
        ),
    ]
