/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContentIndexRouteImport } from './routes/content/index'
import { Route as UserUsernameRouteImport } from './routes/user/$username'
import { Route as ListsIdRouteImport } from './routes/lists/$id'
import { Route as ContentIdRouteImport } from './routes/content/$id'
import { Route as ApiVersionRouteImport } from './routes/api/version'
import { Route as ApiCardsRouteImport } from './routes/api/cards'
import { Route as ApiProxySplatRouteImport } from './routes/api/proxy/$'
import { Route as ApiPerfVitalsRouteImport } from './routes/api/perf/vitals'
import { Route as ApiCoreSplatRouteImport } from './routes/api/core/$'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiAuthRefreshRouteImport } from './routes/api/auth/refresh'
import { Route as ApiAuthLogoutAllRouteImport } from './routes/api/auth/logout-all'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthCsrfRouteImport } from './routes/api/auth/csrf'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentIndexRoute = ContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUsernameRoute = UserUsernameRouteImport.update({
  id: '/user/$username',
  path: '/user/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsIdRoute = ListsIdRouteImport.update({
  id: '/lists/$id',
  path: '/lists/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentIdRoute = ContentIdRouteImport.update({
  id: '/content/$id',
  path: '/content/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVersionRoute = ApiVersionRouteImport.update({
  id: '/api/version',
  path: '/api/version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCardsRoute = ApiCardsRouteImport.update({
  id: '/api/cards',
  path: '/api/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxySplatRoute = ApiProxySplatRouteImport.update({
  id: '/api/proxy/$',
  path: '/api/proxy/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPerfVitalsRoute = ApiPerfVitalsRouteImport.update({
  id: '/api/perf/vitals',
  path: '/api/perf/vitals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoreSplatRoute = ApiCoreSplatRouteImport.update({
  id: '/api/core/$',
  path: '/api/core/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRefreshRoute = ApiAuthRefreshRouteImport.update({
  id: '/api/auth/refresh',
  path: '/api/auth/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutAllRoute = ApiAuthLogoutAllRouteImport.update({
  id: '/api/auth/logout-all',
  path: '/api/auth/logout-all',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCsrfRoute = ApiAuthCsrfRouteImport.update({
  id: '/api/auth/csrf',
  path: '/api/auth/csrf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/api/cards': typeof ApiCardsRoute
  '/api/version': typeof ApiVersionRoute
  '/content/$id': typeof ContentIdRoute
  '/lists/$id': typeof ListsIdRoute
  '/user/$username': typeof UserUsernameRoute
  '/content/': typeof ContentIndexRoute
  '/api/auth/csrf': typeof ApiAuthCsrfRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/logout-all': typeof ApiAuthLogoutAllRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/core/$': typeof ApiCoreSplatRoute
  '/api/perf/vitals': typeof ApiPerfVitalsRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/api/cards': typeof ApiCardsRoute
  '/api/version': typeof ApiVersionRoute
  '/content/$id': typeof ContentIdRoute
  '/lists/$id': typeof ListsIdRoute
  '/user/$username': typeof UserUsernameRoute
  '/content': typeof ContentIndexRoute
  '/api/auth/csrf': typeof ApiAuthCsrfRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/logout-all': typeof ApiAuthLogoutAllRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/core/$': typeof ApiCoreSplatRoute
  '/api/perf/vitals': typeof ApiPerfVitalsRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/api/cards': typeof ApiCardsRoute
  '/api/version': typeof ApiVersionRoute
  '/content/$id': typeof ContentIdRoute
  '/lists/$id': typeof ListsIdRoute
  '/user/$username': typeof UserUsernameRoute
  '/content/': typeof ContentIndexRoute
  '/api/auth/csrf': typeof ApiAuthCsrfRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/logout-all': typeof ApiAuthLogoutAllRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/core/$': typeof ApiCoreSplatRoute
  '/api/perf/vitals': typeof ApiPerfVitalsRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/register'
    | '/search'
    | '/settings'
    | '/terms'
    | '/welcome'
    | '/api/cards'
    | '/api/version'
    | '/content/$id'
    | '/lists/$id'
    | '/user/$username'
    | '/content/'
    | '/api/auth/csrf'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/logout-all'
    | '/api/auth/refresh'
    | '/api/auth/register'
    | '/api/core/$'
    | '/api/perf/vitals'
    | '/api/proxy/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/register'
    | '/search'
    | '/settings'
    | '/terms'
    | '/welcome'
    | '/api/cards'
    | '/api/version'
    | '/content/$id'
    | '/lists/$id'
    | '/user/$username'
    | '/content'
    | '/api/auth/csrf'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/logout-all'
    | '/api/auth/refresh'
    | '/api/auth/register'
    | '/api/core/$'
    | '/api/perf/vitals'
    | '/api/proxy/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/register'
    | '/search'
    | '/settings'
    | '/terms'
    | '/welcome'
    | '/api/cards'
    | '/api/version'
    | '/content/$id'
    | '/lists/$id'
    | '/user/$username'
    | '/content/'
    | '/api/auth/csrf'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/logout-all'
    | '/api/auth/refresh'
    | '/api/auth/register'
    | '/api/core/$'
    | '/api/perf/vitals'
    | '/api/proxy/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiCardsRoute: typeof ApiCardsRoute
  ApiVersionRoute: typeof ApiVersionRoute
  ContentIdRoute: typeof ContentIdRoute
  ListsIdRoute: typeof ListsIdRoute
  UserUsernameRoute: typeof UserUsernameRoute
  ContentIndexRoute: typeof ContentIndexRoute
  ApiAuthCsrfRoute: typeof ApiAuthCsrfRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthLogoutAllRoute: typeof ApiAuthLogoutAllRoute
  ApiAuthRefreshRoute: typeof ApiAuthRefreshRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiCoreSplatRoute: typeof ApiCoreSplatRoute
  ApiPerfVitalsRoute: typeof ApiPerfVitalsRoute
  ApiProxySplatRoute: typeof ApiProxySplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/': {
      id: '/content/'
      path: '/content'
      fullPath: '/content/'
      preLoaderRoute: typeof ContentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$username': {
      id: '/user/$username'
      path: '/user/$username'
      fullPath: '/user/$username'
      preLoaderRoute: typeof UserUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/$id': {
      id: '/lists/$id'
      path: '/lists/$id'
      fullPath: '/lists/$id'
      preLoaderRoute: typeof ListsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$id': {
      id: '/content/$id'
      path: '/content/$id'
      fullPath: '/content/$id'
      preLoaderRoute: typeof ContentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/version': {
      id: '/api/version'
      path: '/api/version'
      fullPath: '/api/version'
      preLoaderRoute: typeof ApiVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cards': {
      id: '/api/cards'
      path: '/api/cards'
      fullPath: '/api/cards'
      preLoaderRoute: typeof ApiCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy/$': {
      id: '/api/proxy/$'
      path: '/api/proxy/$'
      fullPath: '/api/proxy/$'
      preLoaderRoute: typeof ApiProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/perf/vitals': {
      id: '/api/perf/vitals'
      path: '/api/perf/vitals'
      fullPath: '/api/perf/vitals'
      preLoaderRoute: typeof ApiPerfVitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/core/$': {
      id: '/api/core/$'
      path: '/api/core/$'
      fullPath: '/api/core/$'
      preLoaderRoute: typeof ApiCoreSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/refresh': {
      id: '/api/auth/refresh'
      path: '/api/auth/refresh'
      fullPath: '/api/auth/refresh'
      preLoaderRoute: typeof ApiAuthRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout-all': {
      id: '/api/auth/logout-all'
      path: '/api/auth/logout-all'
      fullPath: '/api/auth/logout-all'
      preLoaderRoute: typeof ApiAuthLogoutAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/csrf': {
      id: '/api/auth/csrf'
      path: '/api/auth/csrf'
      fullPath: '/api/auth/csrf'
      preLoaderRoute: typeof ApiAuthCsrfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  WelcomeRoute: WelcomeRoute,
  ApiCardsRoute: ApiCardsRoute,
  ApiVersionRoute: ApiVersionRoute,
  ContentIdRoute: ContentIdRoute,
  ListsIdRoute: ListsIdRoute,
  UserUsernameRoute: UserUsernameRoute,
  ContentIndexRoute: ContentIndexRoute,
  ApiAuthCsrfRoute: ApiAuthCsrfRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthLogoutAllRoute: ApiAuthLogoutAllRoute,
  ApiAuthRefreshRoute: ApiAuthRefreshRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiCoreSplatRoute: ApiCoreSplatRoute,
  ApiPerfVitalsRoute: ApiPerfVitalsRoute,
  ApiProxySplatRoute: ApiProxySplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
